FROM python:3.11-slim


ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

WORKDIR /app


RUN apt-get update \
    && apt-get install -y --no-install-recommends \
       gcc \
       libc-dev \
       libpq-dev \
       build-essential \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY requirements.txt /app/
RUN pip install --upgrade pip
RUN pip install -r requirements.txt

COPY . /app/


RUN mkdir -p /app/static


RUN python manage.py collectstatic --noinput


RUN python manage.py migrate


EXPOSE 8000


CMD ["gunicorn", "--bind", "0.0.0.0:8000", "myproject1.wsgi:application"]
