name: Deploy Infrastructure and Application

on:
  push:
    branches:
      - main
      - dev
      - prod

jobs:
  deploy-infrastructure:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  # Set your desired AWS region

      - name: Set up Terraform
        run: terraform init

      - name: Apply Terraform
        if: github.ref_name == 'dev' || github.ref_name == 'prod'
        run: |
          terraform apply -var-file="${{ github.ref_name }}.tfvars" -auto-approve

  destroy-infrastructure:
    runs-on: ubuntu-latest
    needs: deploy-infrastructure
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Set up Terraform
        run: terraform init

      - name: Request manual approval to destroy
        uses: hmarr/auto-approve-action@v1
        with:
          message: "Please approve the destruction of Terraform resources."

      - name: Destroy Terraform
        if: github.ref_name == 'dev' || github.ref_name == 'prod'
        run: |
          terraform destroy -var-file="${{ github.ref_name }}.tfvars" -auto-approve
